### ISSUE TITLE
Convert mat model to opencv storage xml/yaml model

### ISSUE THREAD

**Issue by TimSC** [wg-perception/PartsBasedDetector#14]
I have compiled PartsBasedDetector without MatlabIO. This can only read models with xml or yaml format. The model training_demo.m code (which I run in octave) saves the model as mat format.

 model = trainmodel(name,pos,neg,K,pa,sbin);
 save('Demo_model.mat', 'model', 'pa', 'sbin', 'name');

There does not seem to be a clear way to covert from .mat to .xml, or am I missing something?

Has matio been considered to read models in C++? http://sourceforge.net/projects/matio/

Regards,

Tim

**Comment by kinjali** [comment]
@hbristow  i am converting .mat file into opencv style using opencv 3.0 and i am getting this 
error: /tmp/ccOrkTWM.o: In function `main':
matlabopencv.cpp:(.text+0xb6): undefined reference to `MatlabIO::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
matlabopencv.cpp:(.text+0x147): undefined reference to `MatlabIO::read()'
matlabopencv.cpp:(.text+0x184): undefined reference to `MatlabIO::close()'
/tmp/ccOrkTWM.o: In function `MatlabIO::~MatlabIO()':
matlabopencv.cpp:(.text._ZN8MatlabIOD2Ev[_ZN8MatlabIOD5Ev]+0xe): undefined reference to `MatlabIO::close()'
collect2: error: ld returned 1 exit status
please help me how to solve it
