### ISSUE TITLE
Compile error doxygen command not found

### ISSUE THREAD

**Issue by chrathan** [wg-perception/PartsBasedDetector#27]
I am trying to compile the project. I ve got two options using gcc for Ubutnu 12.04 I got the same issue as the closed issue https://github.com/wg-perception/PartsBasedDetector/issues/25.  I ve isntalled doxygen but the error remain the same. The second option from windows xp but I not know which compiler to use. I ve installed msvc. The better option is to compile it from ubuntu but how can I fix the error?

make[2]: DOXYGEN_EXECUTABLE-NOTFOUND: Command not found
make[2]: *** [CMakeFiles/PartsBasedDetector_doc] Error 127
make[1]: *** [CMakeFiles/PartsBasedDetector_doc.dir/all] Error 2
make: *** [all] Error 2

My guess was that doxygen was optional.

**Comment by vrabaud** [comment]
closing this one for now, please open a new one about what you cannot do. Thx
