### ISSUE TITLE
OpenCV 3.0 - FilterEngine error

### ISSUE THREAD

**Issue by Bardo91** [wg-perception/PartsBasedDetector#37]
It seems that in OpenCV 3.0 FilterEngine does not exist as public class (https://github.com/Itseez/opencv/issues/4819). So PartBasedDetector library can't be compiled since it uses that class.

**Comment by vrabaud** [comment]
Very busy right now (changing jobs) but I'll get back to that soonish. The OpenCV issues are now on GitHub, please add the proper link

**Comment by ssablak** [comment]
Is there anyone resolved this issure?

**Comment by vrabaud** [comment]
it is on the OpenCV side. Or what would you use to replace its usage in the PartsBased code ?

**Comment by ashokbugude** [comment]
I too am facing same issue

**Comment by trops** [comment]
Turns out there is a bug in opencv 3 so it won't run until a patch is released. Sorry I don't have the link handy but I searched for a while and finally found that out. 

John

**Comment by vrabaud** [comment]
Fixed in master by copying the files over.
