### ISSUE TITLE
Errors while linking ( make command )

### ISSUE THREAD

**Issue by ashokbugude** [wg-perception/PartsBasedDetector#40]
I am able to run cmake command successfully . When I run make , I get below errors

zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Downloads/PartsBasedDetector-master/build$ sudo make 
[  0%] Built target PartsBasedDetector_doc
[ 85%] Built target PartsBasedDetector_lib
[ 92%] Linking CXX executable PartsBasedDetector
CMakeFiles/PartsBasedDetector_bin.dir/demo.cpp.o: In function `cv::_OutputArray::_OutputArray<float>(cv::Mat_<float>&)':
/usr/local/include/opencv2/core/mat.hpp:1149: undefined reference to`vtable for cv::_OutputArray'
/usr/local/include/opencv2/core/mat.hpp:1149: undefined reference to `vtable for cv::_OutputArray'
CMakeFiles/PartsBasedDetector_bin.dir/demo.cpp.o: In function`main':
/home/zayyon/Downloads/PartsBasedDetector-master/src/demo.cpp:90: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/home/zayyon/Downloads/PartsBasedDetector-master/src/demo.cpp:96: undefined reference to`cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libPartsBasedDetector.so: undefined reference to `cv::write(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Mat const&)'
libPartsBasedDetector.so: undefined reference to`cv::FileNode::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libPartsBasedDetector.so: undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
libPartsBasedDetector.so: undefined reference to`cv::_OutputArray::_OutputArray(cv::Mat&)'
libPartsBasedDetector.so: undefined reference to `cv::operator-(cv::MatConstIterator const&, cv::MatConstIterator const&)'
libPartsBasedDetector.so: undefined reference to`cv::FileNodeIterator::readRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*, unsigned long)'
libPartsBasedDetector.so: undefined reference to `cv::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libPartsBasedDetector.so: undefined reference to`cv::operator<<(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libPartsBasedDetector.so: undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
libPartsBasedDetector.so: undefined reference to`cv::write(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libPartsBasedDetector.so: undefined reference to `cv::FileStorage::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libPartsBasedDetector.so: undefined reference to`vtable for cv::_InputArray'
libPartsBasedDetector.so: undefined reference to `cv::putText(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
libPartsBasedDetector.so: undefined reference to `cv::split(cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)'
libPartsBasedDetector.so: undefined reference to`cv::FileStorage::writeRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char const_, unsigned long)'
libPartsBasedDetector.so: undefined reference to `cv::WriteStructContext::WriteStructContext(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libPartsBasedDetector.so: undefined reference to`cv::Formatter::get(char const_)'
libPartsBasedDetector.so: undefined reference to `cv::WriteStructContext::~WriteStructContext()'
libPartsBasedDetector.so: undefined reference to`cv::write(cv::FileStorage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)'
libPartsBasedDetector.so: undefined reference to `cv::namedWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
libPartsBasedDetector.so: undefined reference to`cv::createLinearFilter(int, int, cv::_InputArray const&, cv::Point_<int>, double, int, int, cv::Scalar_<double> const&)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/PartsBasedDetector_bin.dir/build.make:118: recipe for target 'src/PartsBasedDetector' failed
make[2]: **\* [src/PartsBasedDetector] Error 1
CMakeFiles/Makefile2:161: recipe for target 'src/CMakeFiles/PartsBasedDetector_bin.dir/all' failed
make[1]: **\* [src/CMakeFiles/PartsBasedDetector_bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by vrabaud** [comment]
that is fixed in master
